import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'});const checks=[],errors=[];const pass=(ok,label)=>{assert.ok(ok,label);checks.push(label);};
try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});await page.locator('.menu-toggle').tap();await page.locator('#navigation a[href="/blogs"]').tap();await page.locator('.journal-masthead').waitFor();pass(new URL(page.url()).pathname==='/blogs','Mobile Header Blogs navigation');
 await page.locator('.journal-filters button').filter({hasText:'Planning'}).tap();pass(await page.locator('#journal-feature-title').textContent()==='How to Plan Loan Repayments'&&await page.locator('.journal-row').count()===0,'Category filter');await page.locator('.journal-filters button').first().tap();pass(await page.locator('.journal-row').count()===3,'All articles restores collection');
 await page.locator('.journal-read-button').tap();await page.locator('.journal-prose').waitFor();await page.locator('.journal-prose h2').last().scrollIntoViewIfNeeded();await page.waitForTimeout(250);const progress=await page.locator('.journal-story').evaluate(n=>Number(n.style.getPropertyValue('--reading-progress')));pass(progress>0,'Reading progress advances');pass(Math.abs(await page.locator('.journal-reading-progress').evaluate(n=>n.getBoundingClientRect().top)-84)<2,'Reading progress remains below sticky header');
 await page.locator('.footer-navigation a[href="/blogs"]').tap();await page.locator('.journal-masthead').waitFor();pass(true,'Footer Blogs navigation');
 await page.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await page.locator('#admin-username').fill('krish');await page.locator('#admin-password').fill('1153');await page.locator('.blog-login-form button[type=submit]').tap();await page.locator('.blog-dashboard-heading>button').tap();
 for(const [key,value] of Object.entries({title:'Mobile story',excerpt:'A mobile preview.',content:'A first paragraph.\n\n## Heading\n\nA second paragraph.',category:'Mobile'}))await page.locator(`#blog-${key}`).fill(value);
 await page.locator('#blog-status').selectOption('published');await page.getByRole('button',{name:'Save blog',exact:true}).tap();pass(await page.locator('.blog-management-row h2').filter({hasText:'Mobile story'}).count()===1,'Mobile create and publish');
 await page.locator('.blog-management-row').filter({hasText:'Mobile story'}).getByRole('button',{name:'Delete',exact:true}).tap();await page.keyboard.press('Escape');pass(await page.locator('dialog[open]').count()===0,'Escape cancels deletion');
 while(await page.locator('.blog-management-row').count()){await page.locator('.blog-management-row').first().getByRole('button',{name:'Delete',exact:true}).tap();for(let n=0;n<5;n++)await page.keyboard.press('Tab');pass(await page.evaluate(()=>!!document.activeElement.closest('dialog')),'Confirmation traps keyboard focus');await page.getByRole('button',{name:'Delete blog',exact:true}).tap();}
 await page.reload({waitUntil:'networkidle'});pass(await page.locator('.blog-management-row').count()===0,'Deleting every post does not reseed after refresh');await page.goto('http://127.0.0.1:5173/blogs',{waitUntil:'networkidle'});pass(await page.getByRole('heading',{name:'New stories are on their way.'}).isVisible(),'Public empty state');await context.close();
 const reduced=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});await reduced.goto('http://127.0.0.1:5173/blogs',{waitUntil:'networkidle'});pass(await reduced.locator('.journal-page').evaluate(n=>n.getAnimations({subtree:true}).filter(a=>a.playState==='running').length)===0,'Reduced-motion listing');await reduced.locator('.journal-read-button').click();await reduced.locator('.journal-prose').waitFor();pass(await reduced.locator('.journal-page').evaluate(n=>n.getAnimations({subtree:true}).filter(a=>a.playState==='running').length)===0,'Reduced-motion reader');await reduced.screenshot({path:'qa/blogs/final/reduced-reader.png'});await reduced.close();
 const failure=await browser.newPage({viewport:{width:1440,height:900}});failure.on('pageerror',e=>errors.push(e.message));failure.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await failure.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await failure.locator('#admin-username').fill('krish');await failure.locator('#admin-password').fill('1153');await failure.locator('.blog-login-form button[type=submit]').click();await failure.locator('.blog-dashboard-heading>button').click();
 for(const [key,value] of Object.entries({title:'Storage check',excerpt:'Check persistence.',content:'A complete article.',category:'Testing'}))await failure.locator(`#blog-${key}`).fill(value);
 await failure.evaluate(()=>{window.__originalStorageSet=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='sakhi.blogs.v1')throw new DOMException('Full','QuotaExceededError');return window.__originalStorageSet.call(this,key,value);};});await failure.getByRole('button',{name:'Save blog',exact:true}).click();pass(await failure.locator('.blog-admin-notice').textContent()==='The blog could not be saved. Check available browser storage and try again.','Storage failure is reported without false success');await failure.evaluate(()=>{Storage.prototype.setItem=window.__originalStorageSet;});
 await failure.route('**/qa-undecodable-image',route=>route.fulfill({status:200,contentType:'image/png',body:'invalid-image-bytes'}));await failure.locator('#blog-image').fill('/qa-undecodable-image');await failure.waitForTimeout(300);pass(await failure.locator('.blog-editor-image .journal-image>img').count()===0,'Unusable image falls back without broken image icon');await failure.close();
 pass(errors.length===0,'No console errors in edge cases');await writeFile('qa/blogs/final/edge-cases.json',JSON.stringify({checks,errors},null,2));console.log(`${checks.length} mobile, reduced motion, storage, focus and empty-state checks passed.`);
}finally{await browser.close();}
