import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'});await mkdir('qa/blogs/functional',{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage(),reader=await context.newPage();const errors=[],checks=[],requests=[];
for(const p of [page,reader]){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('dialog',d=>{if(d.type()==='beforeunload')d.accept();else{errors.push(`Unexpected ${d.type()}`);d.dismiss();}});}
reader.on('request',r=>requests.push(r.url()));
const check=(condition,label)=>{assert.ok(condition,label);checks.push(label);};
const go=async(p,path)=>{await p.goto(`http://127.0.0.1:5173${path}`,{waitUntil:'networkidle'});};
const row=title=>page.locator('.blog-management-row').filter({has:page.locator('h2',{hasText:title})});
async function fill(values){for(const [key,value] of Object.entries(values))await page.locator(`#blog-${key}`).fill(value);}
try{
 await go(reader,'/blogs/');check(await reader.locator('.journal-lead').count()===1&&await reader.locator('.journal-row').count()===3,'Four demo posts seeded');
 check(await reader.locator('.header a[href="/blogs"]').count()===1&&await reader.locator('.footer-navigation a[href="/blogs"]').count()===1,'Header and Footer Blogs links');
 check(await reader.locator('a[href="/login"]').count()===0&&!requests.some(url=>/admin-auth|admin-page/.test(url)),'Admin code and links absent from public page');
 const urls=await reader.locator('.journal-lead-copy h2 a,.journal-row-copy h3 a').evaluateAll(ns=>ns.map(n=>n.getAttribute('href')));
 for(const url of urls){await go(reader,url);check(await reader.locator('.journal-story-heading h1').count()===1,`Article renders ${url}`);check(await reader.locator('.journal-story-cover .journal-placeholder').count()===1,'Article placeholder present');}
 await reader.locator('.journal-story-top a').click();check(new URL(reader.url()).pathname==='/blogs','Back to Blogs');
 await go(page,'/login');await page.locator('#admin-username').fill('krish');await page.locator('#admin-password').fill('wrong');await page.getByRole('button',{name:'Show password'}).click();check(await page.locator('#admin-password').getAttribute('type')==='text','Show password');await page.getByRole('button',{name:'Hide password'}).click();await page.getByRole('button',{name:'Login',exact:true}).click();check(await page.locator('#login-error').isVisible(),'Wrong credentials rejected inline');
 await page.locator('#admin-password').fill('1153');await page.getByRole('button',{name:'Login',exact:true}).click();await page.locator('.blog-management-list').waitFor();await page.reload({waitUntil:'networkidle'});check(await page.locator('.blog-management-row').count()===4,'Authenticated session survives refresh');
 await page.getByRole('button',{name:'Create blog'}).click();await page.getByRole('button',{name:'Save blog',exact:true}).click();check(await page.locator('#error-title').isVisible(),'Empty editor validation');
 await fill({title:'QA Blog Story',excerpt:'A local editorial test.',content:'An opening paragraph.\n\n## A clear next step\n\nA second paragraph with **bold text**.\n\n- First item\n- Second item',category:'Community'});
 check(await page.locator('#blog-slug').inputValue()==='qa-blog-story','Slug auto-generates');
 await page.getByRole('button',{name:'Preview',exact:true}).click();check(await page.locator('dialog[open] .journal-story-heading h1').textContent()==='QA Blog Story','Unsaved preview renders');await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await row('QA Blog Story').waitFor();check(await row('QA Blog Story').locator('.blog-status').textContent()==='Draft','Create draft');
 await go(reader,'/blogs');check(await reader.getByText('QA Blog Story',{exact:true}).count()===0,'Draft excluded from listing');await go(reader,'/blogs/qa-blog-story');check(await reader.getByRole('heading',{name:'Article not found'}).isVisible(),'Draft excluded from direct public route');
 await row('QA Blog Story').getByRole('button',{name:'Publish',exact:true}).click();await reader.getByRole('heading',{name:'QA Blog Story',exact:true}).waitFor();check(true,'Publishing updates an already-open public tab');
 await row('QA Blog Story').getByRole('button',{name:'Edit',exact:true}).click();await fill({title:'Home',excerpt:'View details',content:'Loans\n\n## Authored words\n\n**Savings** stay as authored.\n\n[Unsafe link](javascript:alert(1))\n\n<img src=x onerror=window.__blogInjected=true>',image:'/assets/sakhi4.jpg'});check(await page.locator('#blog-slug').inputValue()==='qa-blog-story','Editing keeps stable slug');await page.locator('.blog-feature-toggle input').check();await page.getByRole('button',{name:'Save blog',exact:true}).click();await reader.getByRole('heading',{name:'Home',exact:true}).waitFor();check(await reader.locator('.journal-story-deck>p').textContent()==='View details','Edited excerpt updates publicly');
 await reader.locator('.journal-story-cover>img').waitFor();await reader.waitForFunction(()=>document.querySelector('.journal-story-cover>img')?.naturalWidth>0);check(true,'Custom image renders');check(await reader.locator('.journal-prose script,.journal-prose img').count()===0&&await reader.locator('.journal-prose a[href^="javascript:"]').count()===0,'Authored HTML and unsafe links are not executed');
 for(const language of ['hi','mr','en']){await reader.locator('.language-control select').selectOption(language);check(await reader.locator('.journal-story-heading h1').textContent()==='Home'&&await reader.locator('.journal-story-deck>p').textContent()==='View details'&&await reader.locator('.journal-prose>p').first().textContent()==='Loans',`Authored content unchanged in ${language}`);}
 await go(reader,'/blogs');check(await reader.locator('#journal-feature-title').textContent()==='Home','Featured flag chooses lead story');await reader.reload({waitUntil:'networkidle'});check(await reader.locator('#journal-feature-title').textContent()==='Home','Published changes persist after refresh');
 await row('Home').getByRole('button',{name:'Unpublish',exact:true}).click();await reader.waitForFunction(()=>!document.querySelector('#journal-feature-title')?.textContent.includes('Home'));check(await reader.locator('.journal-lead-copy h2,.journal-row h3').filter({hasText:/^Home$/}).count()===0,'Unpublish removes public story live');
 await row('Home').getByRole('button',{name:'Publish',exact:true}).click();await reader.getByRole('heading',{name:'Home',exact:true}).waitFor();
 await page.getByRole('button',{name:'Create blog'}).click();await fill({title:'Duplicate Story',slug:'understanding-fixed-deposits',excerpt:'Duplicate check.',content:'Some content.',category:'Testing'});await page.getByRole('button',{name:'Save blog',exact:true}).click();check(await page.locator('#error-slug').textContent()==='This slug is already in use. Choose another.','Duplicate slug rejected');await page.locator('.blog-admin-back').click();await page.getByRole('button',{name:'Discard changes',exact:true}).click();
 await row('Home').getByRole('button',{name:'Delete',exact:true}).click();check(await page.getByRole('dialog').isVisible(),'Delete confirmation required');await page.getByRole('button',{name:'Cancel',exact:true}).click();check(await row('Home').count()===1,'Delete cancellation preserves post');await row('Home').getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete blog',exact:true}).click();await reader.waitForFunction(()=>!document.querySelector('#journal-feature-title')?.textContent.includes('Home'));check(await row('Home').count()===0,'Confirmed deletion removes admin and public post');await page.reload({waitUntil:'networkidle'});check(await page.locator('.blog-management-row').count()===4,'Deletion persists');
 await page.getByRole('button',{name:'Log out',exact:true}).click();await page.reload({waitUntil:'networkidle'});check(await page.locator('#admin-password').isVisible()&&await page.locator('.blog-management-row').count()===0,'Logout clears session');
 check(errors.length===0,'No console or page errors');
 await writeFile('qa/blogs/functional/results.json',JSON.stringify({checks,errors},null,2));console.log(`${checks.length} workflow checks passed; no console errors.`);
}catch(error){await page.screenshot({path:'qa/blogs/functional/failure-admin.png'});await reader.screenshot({path:'qa/blogs/functional/failure-reader.png'});await writeFile('qa/blogs/functional/failure.json',JSON.stringify({message:error.message,checks,errors},null,2));throw error;}finally{await browser.close();}
