import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'}),checks=[],errors=[];const pass=(ok,label)=>{assert.ok(ok,label);checks.push(label);};
try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await page.locator('#admin-username').fill('krish');await page.locator('#admin-password').fill('1153');await page.locator('.blog-login-form button[type=submit]').click();await page.locator('.blog-dashboard-heading>button').click();
 await page.locator('#blog-title').fill('Formatting and photos');await page.locator('#blog-excerpt').fill('A local editing check.');await page.locator('#blog-category').fill('Testing');
 const rich=page.locator('.editor-rich-text').first();await rich.fill('A useful link');await rich.focus();await page.keyboard.press('Control+A');await page.locator('.editor-block').first().getByRole('button',{name:'Italic',exact:true}).click();pass(await rich.locator('i,em').count()>0,'Italic formatting');
 await rich.focus();await page.keyboard.press('Control+A');await page.locator('.editor-block').first().getByRole('button',{name:'Link',exact:true}).click();await page.getByLabel('Link destination').fill('javascript:alert(1)');await page.getByRole('button',{name:'Apply link'}).click();pass(await page.locator('.editor-link-form [role=alert]').count()===1,'Unsafe links rejected inline');await page.getByLabel('Link destination').fill('https://example.com/guide');await page.getByRole('button',{name:'Apply link'}).click();pass(await rich.locator('a').getAttribute('href')==='https://example.com/guide','Link formatting');
 await page.locator('.editor-add-block>button').last().click();await page.keyboard.press('Escape');pass(await page.locator('.editor-block-menu').count()===0,'Block menu closes with Escape');
 await page.locator('.editor-add-block>button').last().click();await page.locator('.editor-block-menu').getByRole('button',{name:'Image',exact:true}).click();pass(await page.locator('.editor-image-note').count()===1,'Empty image warns editor');
 const webp=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=64;c.height=32;const ctx=c.getContext('2d');ctx.fillStyle='#004ca3';ctx.fillRect(0,0,64,32);return c.toDataURL('image/webp').split(',')[1];});
 await page.locator('.editor-block--image input[type=file]').setInputFiles({name:'local-fixture.webp',mimeType:'image/webp',buffer:Buffer.from(webp,'base64')});await page.locator('.editor-upload-preview').waitFor();pass(await page.locator('.editor-upload-preview').evaluate(n=>n.complete&&n.naturalWidth===64),'WebP upload works on mobile');await page.locator('.editor-block--image').getByLabel('Alt Text',{exact:true}).fill('A blue rectangle');await page.locator('.editor-block--image').getByLabel(/Caption/).fill('   ');await page.locator('#blog-status').selectOption('published');await page.getByRole('button',{name:'Save blog',exact:true}).click();await page.locator('.blog-dashboard-heading').waitFor();
 await page.goto('http://127.0.0.1:5173/blogs/formatting-and-photos',{waitUntil:'networkidle'});await page.locator('.journal-inline-image img').waitFor();pass(await page.locator('figcaption').count()===0,'Blank caption creates no caption spacing');pass(await page.locator('.journal-prose em').count()===1&&await page.locator('.journal-prose a').getAttribute('href')==='https://example.com/guide','Formatting persists in public article');
 const id=await page.evaluate(()=>JSON.parse(localStorage.getItem('sakhi.blogs.v1')).find(p=>p.slug==='formatting-and-photos').blocks.find(b=>b.type==='image').imageId);
 await page.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await page.locator('.blog-management-row').filter({hasText:'Formatting and photos'}).getByRole('button',{name:'Edit',exact:true}).click();await page.locator('.editor-block--image').getByRole('button',{name:'Remove Image',exact:true}).click();pass(await page.locator('.editor-block--image').count()===1,'Remove Image keeps insertion block available');await page.getByRole('button',{name:'Save blog',exact:true}).click();await page.locator('.blog-dashboard-heading').waitFor();await page.waitForTimeout(150);pass(await page.evaluate(async id=>!await(await import('/src/blogs/asset-repository.js')).AssetRepository.getImage(id),id),'Removing inline media cleans unused asset');await page.goto('http://127.0.0.1:5173/blogs/formatting-and-photos',{waitUntil:'networkidle'});pass(await page.locator('.journal-inline-image').count()===0,'Empty image block omitted publicly');
 await page.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await page.locator('.blog-dashboard-heading>button').click();await page.locator('#blog-title').fill('Discarded photo');await page.locator('.editor-upload--featured input[type=file]').setInputFiles('public/assets/sakhi4.jpg');await page.locator('.editor-upload--featured img').waitFor();const orphan=await page.evaluate(async()=>{const request=indexedDB.open('sakhi-blog-assets');const db=await new Promise(resolve=>request.onsuccess=()=>resolve(request.result));const tx=db.transaction('images'),get=tx.objectStore('images').getAll();const rows=await new Promise(resolve=>get.onsuccess=()=>resolve(get.result));db.close();return rows.sort((a,b)=>b.createdAt-a.createdAt)[0].id;});await page.locator('.blog-admin-back').click();await page.getByRole('button',{name:'Discard changes',exact:true}).click();await page.waitForTimeout(150);pass(await page.evaluate(async id=>!await(await import('/src/blogs/asset-repository.js')).AssetRepository.getImage(id),orphan),'Discarded upload cleaned');
 await page.evaluate(async()=>{const{BlogRepository:r}=await import('/src/blogs/repository.js');const p=r.getPosts().find(p=>p.slug==='formatting-and-photos');r.updatePost(p.id,{...p,blocks:[...p.blocks,{id:'missing-block',type:'image',imageId:'missing-file',alt:'',caption:''}],featuredImageId:'missing-feature'});});await page.reload({waitUntil:'networkidle'});await page.locator('.blog-management-row').filter({hasText:'Formatting and photos'}).getByRole('button',{name:'Edit',exact:true}).click();await page.locator('.editor-block--image').last().getByRole('alert').waitFor();pass(await page.locator('.editor-block--image').last().getByRole('alert').isVisible(),'Missing stored image warns editor');await page.goto('http://127.0.0.1:5173/blogs/formatting-and-photos',{waitUntil:'networkidle'});pass(await page.locator('.journal-inline-image img,.journal-story-cover>img').count()===0,'Missing media shows placeholder or is omitted, no broken image');
 pass(errors.length===0,'No console errors');await writeFile('qa/blog-editor/edge-results.json',JSON.stringify({checks,errors},null,2));console.log(`${checks.length} formatting, WebP, missing-media and cleanup checks passed.`);
}finally{await browser.close();}
