import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'}),errors=[],results=[];await mkdir('qa/blog-editor/screenshots',{recursive:true});
try{for(const [width,height] of [[1440,900],[1920,1080],[2560,1440],[1024,1366],[768,1024],[390,844],[375,812]]){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(`${width}: ${e.message}`));page.on('console',m=>{if(m.type()==='error')errors.push(`${width}: ${m.text()}`);});page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await page.locator('#admin-username').fill('krish');await page.locator('#admin-password').fill('1153');await page.locator('.blog-login-form button[type=submit]').click();await page.locator('.blog-dashboard-heading>button').click();
 await page.locator('#blog-title').fill('A little clarity for your savings');await page.locator('#blog-excerpt').fill('Questions, ideas and small steps to help you plan your next chapter.');await page.locator('#blog-category').fill('Financial Education');await page.locator('.editor-rich-text').fill('Start with what matters to you. A clear goal and a moment to reflect can help you ask the right questions before your next step.');
 const add=async type=>{await page.locator('.editor-add-block>button').last().click();await page.locator('.editor-block-menu').getByRole('button',{name:type,exact:true}).click();};
 await add('Heading');await page.locator('.editor-block--heading .editor-rich-text').fill('Make space for a plan');await page.locator('.editor-block--heading select').selectOption('3');
 await add('Image');await page.locator('.editor-block--image input[type=file]').setInputFiles('public/assets/sakhi4.jpg');await page.locator('.editor-upload-preview').waitFor();await page.locator('.editor-block--image').getByLabel('Alt Text',{exact:true}).fill('A stack of Indian rupee notes');await page.locator('.editor-block--image').getByLabel(/Caption/).fill('An illustration for the article.');
 await page.locator('.editor-upload--featured input[type=file]').setInputFiles('public/assets/sakhi3.png');await page.locator('.editor-upload--featured img').waitFor();await page.locator('#blog-featuredImageAlt').fill('Indian rupee notes arranged in a fan');await page.locator('.editor-block--image').getByRole('button',{name:'Move Up',exact:true}).click();await page.locator('.editor-block--image').getByRole('button',{name:'Move Down',exact:true}).click();
 await page.locator('#editor-seo summary').click();await page.locator('#blog-focusKeyword').fill('savings');await page.locator('#blog-seoTitle').fill('A Little Clarity for Your Savings: A Simple Guide | Sakhi');await page.locator('#blog-metaDescription').fill('Explore practical questions and ideas for your savings plan. Give yourself a clear starting point and make room to reflect before you take the next step.');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}: editor overflows`);
 const outside=await page.locator('.blog-editor :is(input,textarea,button,select,[contenteditable=true])').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length&&!n.matches('input[type=file]')&&getComputedStyle(n).visibility!=='hidden').filter(n=>{const b=n.getBoundingClientRect();return b.left<0||b.right>innerWidth+1;}).map(n=>n.outerHTML.slice(0,120)));assert.deepEqual(outside,[],`${width}: offscreen controls`);
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`qa/blog-editor/screenshots/${width}-top.png`});await page.locator('.editor-blocks').screenshot({path:`qa/blog-editor/screenshots/${width}-blocks.png`});await page.locator('#editor-seo').screenshot({path:`qa/blog-editor/screenshots/${width}-seo.png`});
 for(const language of ['hi','mr']){await page.locator('.language-control select').selectOption(language);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('#blog-title').inputValue(),'A little clarity for your savings');if(width===390)await page.locator('#editor-seo').screenshot({path:`qa/blog-editor/screenshots/${width}-${language}-seo.png`});}
 const missing=await page.evaluate(()=>[...window.__sakhiMissingTranslations||[]]);assert.deepEqual(missing,[],`${width}: untranslated interface`);results.push({width,height,upload:true,reorder:true,overflow:false,languages:['en','hi','mr'],missing});await page.close();
}assert.deepEqual(errors,[]);await writeFile('qa/blog-editor/responsive-results.json',JSON.stringify({results,errors},null,2));console.log('Seven editor viewports, uploads, block reordering and three languages passed.');}finally{await browser.close();}
