import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome'}),checks=[],errors=[];
const pass=(value,label)=>{assert.ok(value,label);checks.push(label);console.log(label);};
const getPosts=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('sakhi.blogs.v1')));
const block=(page,type)=>page.locator(`.editor-block--${type}`).last();
const add=async(page,type)=>{await page.locator('.editor-add-block>button').last().click();await page.locator('.editor-block-menu').getByRole('button',{name:type,exact:true}).click();};
const edit=async(page,title)=>page.locator('.blog-management-row').filter({has:page.getByRole('heading',{name:title,exact:true})}).first().getByRole('button',{name:'Edit',exact:true}).click();
const save=async page=>{await page.getByRole('button',{name:'Save blog',exact:true}).click();await page.locator('.blog-dashboard-heading').waitFor();};
const assetExists=(page,id)=>page.evaluate(async id=>!!await(await import('/src/blogs/asset-repository.js')).AssetRepository.getImage(id),id);
try{
 const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),page=await context.newPage(),publicPage=await context.newPage();
 for(const p of [page,publicPage]){p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('dialog',d=>d.accept());}
 await page.goto('http://127.0.0.1:5173/login',{waitUntil:'networkidle'});await page.locator('#admin-username').fill('krish');await page.locator('#admin-password').fill('wrong');await page.locator('.blog-login-form button[type=submit]').click();pass(await page.locator('#login-error').isVisible(),'Wrong credentials stay rejected');await page.locator('#admin-password').fill('1153');await page.locator('.blog-login-form button[type=submit]').click();
 pass(await page.locator('.blog-management-row').count()===4,'Four seeded posts preserved');
 await edit(page,'Understanding Fixed Deposits');pass(await page.locator('.editor-block').count()>5,'Existing Markdown restores as blocks');
 pass(await page.locator('.editor-block--heading').count()===3,'Existing headings preserved');pass(await page.locator('textarea#blog-content,input#blog-image').count()===0,'Old giant textarea and image URL field removed');
 await page.locator('#blog-slug').fill('existing-fixed-deposits');await save(page);
 await page.locator('.blog-dashboard-heading>button').click();
 const title='Understanding Fixed Deposits',seo='Understanding Fixed Deposits: A Simple Guide | Sakhi',description='Learn how fixed deposits work and what to consider when using them as part of a disciplined savings plan.';
 await page.locator('#blog-title').fill(title);pass(await page.locator('#blog-slug').inputValue()==='understanding-fixed-deposits','Slug auto-generates');await page.locator('#blog-excerpt').fill('A clear introduction to fixed deposits.');await page.locator('#blog-category').fill('Savings');await page.getByLabel('Tags',{exact:true}).fill('Fixed Deposit');await page.getByLabel('Tags',{exact:true}).press('Enter');
 await block(page,'paragraph').locator('.editor-rich-text').fill('First paragraph. These are the opening words of our article.');
 await block(page,'paragraph').locator('.editor-rich-text').focus();await page.keyboard.press('Control+A');await block(page,'paragraph').getByRole('button',{name:'Bold',exact:true}).click();pass(await block(page,'paragraph').locator('.editor-rich-text :is(b,strong)').count()>0,'Bold formatting without Markdown');
 await add(page,'Heading');await block(page,'heading').locator('.editor-rich-text').fill('Planning your savings');await block(page,'heading').getByLabel('Heading level').selectOption('2');pass((await block(page,'heading').locator('select option').allTextContents()).join(',')==='H2,H3','Only H2/H3 body headings');
 await add(page,'Image');const imageBlock=block(page,'image');await imageBlock.locator('input[type=file]').setInputFiles('public/assets/sakhi3.png');await imageBlock.locator('.editor-upload-preview').waitFor();await imageBlock.getByLabel('Alt Text',{exact:true}).fill('A fan of Indian rupee notes');await imageBlock.getByLabel(/Caption/).fill('A sample savings illustration.');
 await add(page,'Paragraph');await block(page,'paragraph').locator('.editor-rich-text').fill('Last paragraph. Continue the article after the photo.');
 await add(page,'Bullet List');await block(page,'bulletList').locator('textarea').fill('Review your goal\nKeep your records');
 await add(page,'Numbered List');await block(page,'numberedList').locator('textarea').fill('Read the terms\nAsk your questions');
 await add(page,'Quote');await block(page,'quote').locator('.editor-rich-text').fill('Every next step begins with understanding.');
 await page.locator('.editor-upload--featured input[type=file]').setInputFiles('public/assets/sakhi4.jpg');await page.locator('.editor-upload--featured img').waitFor();await page.locator('#blog-featuredImageAlt').fill('A stack of Indian rupee notes');pass(await page.locator('.editor-upload--featured').getByRole('button',{name:'Replace Image',exact:true}).isVisible(),'Featured upload previews before saving');
 await page.locator('#editor-seo summary').click();await page.locator('#blog-focusKeyword').fill('fixed deposits');await page.locator('#blog-seoTitle').fill(seo);await page.locator('#blog-metaDescription').fill(description);await page.getByLabel('Related Keywords',{exact:true}).fill('savings');await page.getByLabel('Related Keywords',{exact:true}).press('Enter');
 pass((await page.locator('.editor-search-preview').textContent()).includes(seo)&&(await page.locator('.editor-search-preview').textContent()).includes(description),'Search Preview updates live');pass(await page.locator('.editor-seo-check li').filter({hasText:'Focus Keyword in Meta Description'}).getAttribute('data-seo-status')==='Good','SEO Check reacts to keyword');await page.locator('#blog-focusKeyword').fill('different phrase');pass(await page.locator('.editor-seo-check li').filter({hasText:'Focus Keyword in Meta Description'}).getAttribute('data-seo-status')==='Needs Attention','SEO Check responds to changed keyword');await page.locator('#blog-focusKeyword').fill('fixed deposits');
 await page.getByRole('button',{name:'Preview',exact:true}).click();await page.locator('dialog .journal-inline-image img').waitFor();pass((await page.locator('dialog .journal-prose').evaluate(n=>[...n.children].map(c=>c.tagName))).join(',')==='P,H2,FIGURE,P,UL,OL,BLOCKQUOTE','Unsaved preview preserves block order');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.locator('.blog-dashboard-heading').waitFor();let post=(await getPosts(page)).find(p=>p.slug==='understanding-fixed-deposits');const featured=post.featuredImageId,inline=post.blocks.find(b=>b.type==='image').imageId;
 pass(!!featured&&!!inline,'Stable image IDs stored in Blog data');pass(!JSON.stringify(post).includes('blob:')&&!JSON.stringify(post).includes('data:image'),'No Blob URL or Base64 images in localStorage');pass(await assetExists(page,featured)&&await assetExists(page,inline),'Image blobs stored in IndexedDB');
 await page.reload({waitUntil:'networkidle'});await edit(page,title);await page.locator('.editor-upload--featured img').waitFor();await imageBlock.locator('.editor-upload-preview').waitFor();pass(await page.locator('#blog-featuredImageAlt').inputValue()==='A stack of Indian rupee notes','Featured image and alt survive refresh');pass(await imageBlock.getByLabel(/Caption/).inputValue()==='A sample savings illustration.','Inline image, alt and caption restore');await page.locator('#editor-seo summary').click();pass(await page.locator('#blog-seoTitle').inputValue()===seo&&await page.locator('#blog-metaDescription').inputValue()===description,'SEO fields restore');pass((await page.locator('.editor-tag-values').allTextContents()).join(' ').includes('Fixed Deposit'),'Tags and related keywords restore');
 await publicPage.goto('http://127.0.0.1:5173/blogs/understanding-fixed-deposits',{waitUntil:'networkidle'});pass(await publicPage.getByRole('heading',{name:'Article not found'}).isVisible(),'Draft with uploads remains private');
 await page.locator('#blog-status').selectOption('published');await save(page);await publicPage.reload({waitUntil:'networkidle'});await publicPage.locator('.journal-inline-image img').waitFor();
 pass(await publicPage.title()===seo,'Public document title uses SEO Title');pass(await publicPage.locator('meta[name=description]').getAttribute('content')===description,'Public meta description uses authored summary');pass(await publicPage.locator('meta[name=keywords]').count()===0,'No meta keywords tag');pass(await publicPage.locator('h1').count()===1&&await publicPage.locator('h1').textContent()===title,'Article title is the only H1');pass(await publicPage.locator('.journal-story-cover>img').getAttribute('alt')==='A stack of Indian rupee notes','Featured public alt text');pass(await publicPage.locator('.journal-inline-image img').getAttribute('alt')==='A fan of Indian rupee notes','Inline public alt text');pass(await publicPage.locator('figcaption').textContent()==='A sample savings illustration.','Public caption');pass((await publicPage.locator('.journal-prose').evaluate(n=>[...n.children].map(c=>c.tagName))).join(',')==='P,H2,FIGURE,P,UL,OL,BLOCKQUOTE','Public block order');
 await publicPage.goto('http://127.0.0.1:5173/blogs',{waitUntil:'networkidle'});pass(await publicPage.locator(`a[href='/blogs/understanding-fixed-deposits'] img`).count()>0,'Listing uses uploaded Featured Image');
 await edit(page,title);await block(page,'image').getByRole('button',{name:'Move Up',exact:true}).click();await block(page,'image').getByRole('button',{name:'Move Down',exact:true}).click();await block(page,'image').getByRole('button',{name:'Move Down',exact:true}).click();await block(page,'image').locator('input[type=file]').setInputFiles('public/assets/sakhi4.jpg');await page.waitForFunction(()=>document.querySelector('.editor-block--image img')?.naturalWidth===678);
 await page.locator('.editor-upload--featured input[type=file]').setInputFiles('public/assets/sakhi3.png');await page.waitForFunction(()=>document.querySelector('.editor-upload--featured img')?.naturalWidth===360);await save(page);post=(await getPosts(page)).find(p=>p.slug==='understanding-fixed-deposits');const replacementFeatured=post.featuredImageId,replacementInline=post.blocks.find(b=>b.type==='image').imageId;
 await page.waitForTimeout(150);pass(!await assetExists(page,featured)&&!await assetExists(page,inline),'Replaced unused assets cleaned after save');await publicPage.goto('http://127.0.0.1:5173/blogs/understanding-fixed-deposits',{waitUntil:'networkidle'});await publicPage.locator('.journal-inline-image img').waitFor();pass((await publicPage.locator('.journal-prose').evaluate(n=>[...n.children].map(c=>c.tagName))).join(',')==='P,H2,P,FIGURE,UL,OL,BLOCKQUOTE','Reordered image persists publicly');
 // Share a reference through the repository to prove cleanup never deletes a
 // saved draft's asset when another article stops using it.
 await page.evaluate(async imageId=>{const{BlogRepository:r}=await import('/src/blogs/repository.js');const p=r.getPosts().find(p=>p.slug==='existing-fixed-deposits');r.updatePost(p.id,{...p,status:'draft',featuredImageId:imageId});},replacementFeatured);await page.reload({waitUntil:'networkidle'});
 await edit(page,title);await page.locator('.editor-upload--featured').getByRole('button',{name:'Remove Image',exact:true}).click();await block(page,'image').getByRole('button',{name:'Remove block',exact:true}).click();await page.locator('#editor-seo summary').click();await page.locator('#blog-seoTitle').fill('');await page.locator('#blog-metaDescription').fill('');await save(page);await page.waitForTimeout(100);pass(await assetExists(page,replacementFeatured),'Shared image survives another post removal');pass(!await assetExists(page,replacementInline),'Removed inline image cleaned after save');await publicPage.reload({waitUntil:'networkidle'});pass(await publicPage.locator('.journal-story-cover>img').count()===0,'Featured removal restores placeholder');pass(await publicPage.locator('.journal-inline-image').count()===0,'Removed inline image leaves no caption or gap');pass(await publicPage.title()===title+' | Sakhi','Empty SEO title falls back');pass(await publicPage.locator('meta[name=description]').getAttribute('content')==='A clear introduction to fixed deposits.','Empty description falls back to excerpt');
 await edit(page,title);await page.locator('#blog-slug').fill(' Existing Fixed Deposits !!! ');await page.locator('#blog-slug').blur();pass(await page.locator('#blog-slug').inputValue()==='existing-fixed-deposits','Manual slug normalizes');await page.getByRole('button',{name:'Save blog',exact:true}).click();pass(await page.locator('#error-slug').textContent()==='This URL is already being used by another Blog. Please choose a different slug.','Duplicate URL rejected clearly');await page.locator('#blog-slug').fill('understanding-fixed-deposits');
 await page.locator('.editor-upload--featured input[type=file]').setInputFiles({name:'large.png',mimeType:'image/png',buffer:Buffer.alloc(10*1024*1024+1)});pass((await page.locator('.editor-upload--featured [role=alert]').textContent()).includes('under 10 MB'),'Oversized image rejected inline');await page.locator('.editor-upload--featured input[type=file]').setInputFiles({name:'not-image.txt',mimeType:'text/plain',buffer:Buffer.from('test')});pass((await page.locator('.editor-upload--featured [role=alert]').textContent()).includes('JPG, PNG or WebP'),'Unsupported format rejected');await page.locator('.editor-upload--featured input[type=file]').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('invalid')});pass((await page.locator('.editor-upload--featured [role=alert]').textContent()).includes('could not be opened'),'Corrupt image rejected');
 await page.locator('.blog-admin-back').click();if(await page.locator('dialog[open]').count())await page.getByRole('button',{name:'Discard changes',exact:true}).click();await page.locator('.blog-management-row').filter({has:page.getByRole('heading',{name:title,exact:true})}).first().getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();pass((await getPosts(page)).some(p=>p.title===title&&p.slug==='understanding-fixed-deposits'),'Delete confirmation cancels');
 await page.locator('.blog-management-row').filter({has:page.getByRole('heading',{name:title,exact:true})}).first().getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete blog',exact:true}).click();await publicPage.reload({waitUntil:'networkidle'});pass(await publicPage.getByRole('heading',{name:'Article not found'}).isVisible(),'Delete removes public article');
 pass(errors.length===0,'No console errors');await writeFile('qa/blog-editor/workflow-results.json',JSON.stringify({checks,errors},null,2));console.log(`${checks.length} block, upload, storage, SEO and preservation checks passed.`);
}finally{await browser.close();}
